[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/login"
  to = "http://ec2-54-190-97-137.us-west-2.compute.amazonaws.com:5000/"
  status = 200
  force = true

[[redirects]]
  from = "/register"
  to = "http://ec2-54-190-97-137.us-west-2.compute.amazonaws.com:5000/"
  status = 200
  force = true
