[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/login"
  to = "https://simple-web-community.herokuapp.com/login"
  status = 200
  force = true

[[redirects]]
  from = "/register"
  to = "https://simple-web-community.herokuapp.com/register"
  status = 200
  force = true